ethereum_network = "Goerli"
beacon_endpoint = "https://lodestar-goerli.chainsafe.io"
eth1_endpoint = "https://lodestar-goerlirpc.chainsafe.io"
eth_requests_timeout_seconds = 60
validate_updates = true
verify_bls_signature = true
hashes_gc_threshold = 51000
beacon_rpc_version = "V1_5"

substrate_network_name = "ggxchain"
substrate_endpoint = "ws://127.0.0.1:9944"
path_to_signer_secret_key = "./secret-key"
# We need to rotate it pretty often -> https://beaconstate-goerli.chainsafe.io/
init_block_root="0xc94a175e905659a45f43409d5228eb99510ad130c201951171f0eee3c231ade3"
