apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ggx-node
spec:
  serviceName: ggx-node
  selector:
    matchLabels:
      app: ggx-node
  replicas: 1
  template:
    metadata:
      labels:
        app: ggx-node
    spec:
      #nodeSelector:
      #  environment: brooklyn # EKS worker-node-groups will be defined later on
      initContainers:
        - name: json-installer
          image: busybox
          imagePullPolicy: "IfNotPresent"
          command: ["wget", "-O", "/tmp/$(CHAINSPEC)", "https://golden-gate-substrate-chain-spec-files.s3.eu-central-1.amazonaws.com/$(CHAINSPEC)" ]
          envFrom:
            - configMapRef:
                name: ggx-node-config
          volumeMounts: 
            - name: chain-info
              mountPath: /tmp
      containers:
        - name: ggx-node
          image: public.ecr.aws/f8n4k6v0/golden-gate-node:e23018bd
          imagePullPolicy: "IfNotPresent"
          command: [ "/usr/src/app/target/release/golden-gate-node" ]
          ##args: ["--base-path=/chain-data", "--name=$(NAME)", "--chain=/chain-info/$(CHAINSPEC)", "--validator", "--password=$(PASSWORD)", "--telemetry-url=$(TELEMETRY)", "--bootnodes=$(BOOT_NODES)"]
          envFrom:
            - configMapRef:
                name: ggx-node-config
            - secretRef:
                name: ggx-node-secret
          resources:
            requests:
              cpu: 1000m
              memory: 2G
            limits:
              cpu: 4000m
              memory: 8G
          ports:
            - containerPort: 9944
            - containerPort: 9933
            - containerPort: 30333
          volumeMounts:
            - name: ggx-node-data
              mountPath: /chain-data
            - name: chain-info
              mountPath: /chain-info
      volumes:
        - name: chain-info
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: ggx-node-data
      labels:
        app: ggx-node
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
