apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ggx-sydney-archive
  namespace: ggx-sydney
spec:
  serviceName: ggx-sydney-archive
  selector:
    matchLabels:
      app: ggx-sydney-archive
  replicas: 1
  template:
    metadata:
      labels:
        app: ggx-sydney-archive
    spec:
      initContainers:
        - name: json-installer
          image: busybox
          imagePullPolicy: "IfNotPresent"
          command: ["wget", "-O", "/tmp/$(CHAINSPEC)", "https://golden-gate-substrate-chain-spec-files.s3.eu-central-1.amazonaws.com/$(CHAINSPEC)" ]
          envFrom:
            - configMapRef:
                name: ggx-node-config
          volumeMounts: 
            - name: chain-info
              mountPath: /tmp
      containers:
        - name: ggx-sydney-archive
          image: public.ecr.aws/f8n4k6v0/golden-gate-node:sydney-f4382271
          imagePullPolicy: "IfNotPresent"
          command: [ "/usr/src/app/target/release/golden-gate-node" ]
          args: ["--base-path=/chain-data", "--name=$(NAME)", "--chain=/chain-info/$(CHAINSPEC)", "--pruning=archive", "--state-pruning=archive", "--blocks-pruning=archive", "--password=$(PASSWORD)", "--telemetry-url=$(TELEMETRY)", "--bootnodes=/ip4/3.69.173.157/tcp/30333/p2p/12D3KooWSriyuFSmvuc188UWqV6Un7YYCTcGcoSJcoyhtTZEWi1n"]
          envFrom:
            - configMapRef:
                name: ggx-node-config
            - secretRef:
                name: ggx-node-secret
          resources:
            requests:
              cpu: 1000m
              memory: 2G
            limits:
              cpu: 4000m
              memory: 8G
          ports:
            - containerPort: 9944
            - containerPort: 9933
            - containerPort: 30333
          volumeMounts:
            - name: ggx-sydney-archive
              mountPath: /chain-data
            - name: chain-info
              mountPath: /chain-info
      volumes:
        - name: chain-info
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: ggx-sydney-archive
      labels:
        app: ggx-sydney-archive
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
