name: GGX-Substrate-Node

# The ref given is fully-formed, meaning that for branches the format is refs/heads/<branch_name>, for pull requests it is refs/pull/<pr_number>/merge, and for tags it is refs/tags/<tag_name>
on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

env:
  NIX_VERSION: nix-2.13.2
  NIXPKGS_CHANNEL: nixos-22.11
  CACHIX_NAME: golden-gate-ggx
  OCTOLYTICS_DIMENSION_REPOSITORY_ID: 590614152
  GIT_LFS_SKIP_SMUDGE: 1

jobs:
  common:
    if: github.event_name == 'pull_request'
    runs-on: buildjet-32vcpu-ubuntu-2204
    container: ggxdocker/ggxnode-dev:v1
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - run: git config --global --add safe.directory "*"
      - uses: technote-space/get-diff-action@v6.1.2
        id: git-diff
        with:
          PATTERNS: |
            **/**.rs
            Cargo.lock

      - uses: dsherret/rust-toolchain-file@v1
        if: steps.git-diff.outputs.diff

      - uses: buildjet/cache@v4
        if: steps.git-diff.outputs.diff
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: fmt
        run: cargo fmt --all -- --check
        if: steps.git-diff.outputs.diff

      - name: clippy + build
        if: steps.git-diff.outputs.diff
        run: |
          packages="runtime-common ggxchain-runtime-brooklyn ggxchain-runtime-sydney"
          for pkg in $packages; do
              cargo clippy --package=$pkg -- -D warnings
              cargo build --locked --package=$pkg --release
          done

      - name: run tests common
        if: steps.git-diff.outputs.diff
        run: cargo test --release --package runtime-common


  build-lint:
    strategy:
      matrix:
        runtime: [sydney, brooklyn]
      fail-fast: false
    if: github.event_name == 'pull_request'
    ## Run only if a PR is made for the main branch
    runs-on: buildjet-32vcpu-ubuntu-2204
    container: ggxdocker/ggxnode-dev:v1
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - run: git config --global --add safe.directory "*"
      - uses: technote-space/get-diff-action@v6.1.2
        id: git-diff
        with:
          PATTERNS: |
            **/**.rs
            Cargo.lock

      - uses: dsherret/rust-toolchain-file@v1
        if: steps.git-diff.outputs.diff

      - uses: buildjet/cache@v4
        if: steps.git-diff.outputs.diff
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: clippy + build + test
        if: steps.git-diff.outputs.diff
        run: |
          cargo clippy --package=ggxchain-node --no-default-features --features=${{ matrix.runtime }} -- -D warnings
          cargo build --locked --package=ggxchain-node --release --no-default-features --features=${{ matrix.runtime }}
          cargo test --locked --package=ggxchain-node --release --no-default-features --features=${{ matrix.runtime }}


  docker-build-sydney:
    if: github.ref == 'refs/heads/main'
    runs-on: buildjet-32vcpu-ubuntu-2204
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          ## This has to be either 'us-east-1' or 'us-west-2' for public ECR

      - name: Log in to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set Image Tag
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Build, tag, and upload the docker image
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: k7w7q6c4
          REPOSITORY: ggxchain-node
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:sydney-$SHORT_SHA -f Dockerfile.sydney .
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:sydney-$SHORT_SHA

      - name: Store Image Tag on AWS S3
        env:
          S3_BUCKET: ggx-docker-image-tags
        run: |
          echo "Uploading Docker Image Tag to S3 Bucket as this workflow's artifact"
          echo "$SHORT_SHA" > sydney_version
          aws --region eu-central-1 s3 cp sydney_version s3://$S3_BUCKET/sydney_version
          echo "This image will be used in the future deployments.."

      - name: Log out of Amazon ECR
        run: docker logout ${{ steps.login-ecr-public.outputs.registry }}

  docker-build-brooklyn:
    if: github.ref == 'refs/heads/main'
    runs-on: buildjet-32vcpu-ubuntu-2204
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          ## This has to be either 'us-east-1' or 'us-west-2' for public ECR

      - name: Log in to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set Image Tag
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Build, tag, and upload the docker image
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: k7w7q6c4
          REPOSITORY: ggxchain-node
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:brooklyn-$SHORT_SHA -f Dockerfile.brooklyn .
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:brooklyn-$SHORT_SHA

      - name: Store Image Tag on AWS S3
        env:
          S3_BUCKET: ggx-docker-image-tags
        run: |
          echo "Uploading Docker Image Tag to S3 Bucket as this workflow's artifact"
          echo "$SHORT_SHA" > brooklyn_version
          aws --region eu-central-1 s3 cp brooklyn_version s3://$S3_BUCKET/brooklyn_version
          echo "This image will be used in the future deployments.."

      - name: Log out of Amazon ECR
        run: docker logout ${{ steps.login-ecr-public.outputs.registry }}
