name: "pull-request-write"
on:
  push:
    branches:
      - main
    path:
      - "**/*.md"
      - "**/*.MD"

  pull_request:
    path:
      - "**/*.md"
      - "**/*.MD"

permissions:
  contents: read

jobs:
  lint-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          command: config
          globs: |
            .markdownlint-cli2.yaml
            **/*.md
            **/*.MD